# Site settings
title: Portale Ricerca e Sviluppo Rete Ferroviaria Italiana
email: mail@rfi.it
description: > # il portale ufficiale di ricerca e sviluppo di rete ferroviaria italiana (gruppo FS).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: RESrfi
github_username:  RESrfi

# Build settings
markdown: kramdown
